name: synchmap
description: A mapping application with text denoising and text-to-speech features.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`.
publish_to: 'none' 

# Version
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6      # For picking images
  http: ^0.13.5             # For HTTP requests
  path: ^1.8.2              # For path manipulation
  path_provider: ^2.0.11    # For accessing device directories
  audioplayers: ^1.1.1      # For audio playback
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg